import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
  },
  input: {
    height: 48,
    borderRadius: 5,
    overflow: 'hidden',
    backgroundColor: 'white',
    marginTop: 10,
    marginBottom: 10,
    marginLeft: 30,
    marginRight: 30,
    paddingLeft: 16,
  },
  pcard: {
    height: 'auto',
    width: '100%',
    borderRadius: 15,
    overflow: 'hidden',
    backgroundColor: '#f7fbf3c9',
    borderColor: '#4b5b4b71',
    borderWidth: 1,
    marginTop: 15,
    marginBottom: 15,
    alignItems: 'center',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: 'black',
    marginTop: 30,
    marginBottom: 10,
  },
  description: {
    fontSize: 16,
    fontWeight: 'bold',
    color: 'black',
    alignItems: 'center',
    justifyContent: 'center',
    margin: 5,
  },
  values: {
    fontSize: 16,
    color: 'black',
    marginBottom: 5,
    marginLeft: 1,
    marginRight: 1,
  },
  meanValues: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    marginBottom: 20,
    marginLeft: 8,
    marginRight: 8,
  },
  list: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 30,
    width: '100%',
  },
  buttons: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
  },
  info: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
});
